apiVersion: v2
name: geonode
version: 0.1.4
type: application
description: Helm Chart for Geonode
home: https://geonode.org/
sources:
  - https://github.com/one-acre-fund/oaf-public-charts/tree/main/charts/geonode
maintainers:
  - name: Yann-J
    email: yann.jouanique@gmail.com
dependencies:
  - name: postgresql
    version: ~10.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: ~8.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
