{{ if .Values.ingress.enabled }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.general.hostname }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  name: api
            path: /studio-api/?(.*)
  {{ if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | nindent 4 }}
  {{ end }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ui
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.general.hostname }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-ui
                port:
                  name: ui
            path: /
  {{ if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | nindent 4 }}
  {{ end }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ws
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-connect-timeout: "3600"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/send-timeout: "3600"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: {{ .Values.general.hostname }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-ws
                port:
                  name: ws
            path: /ws/?(.*)
  {{ if .Values.ingress.tls }}
  tls:
    {{- .Values.ingress.tls | toYaml | nindent 4 }}
  {{ end }}
{{ end }}
