# PVC for media uploads
{{- if .Values.general.mediaStorage.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kobo-media
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.general.mediaStorage.accessMode }}
  {{- if coalesce .Values.general.mediaStorage.storageClass .Values.global.storageClass }}
  storageClassName: {{ coalesce .Values.general.mediaStorage.storageClass .Values.global.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.general.mediaStorage.size }}
{{- end -}}
