{{- if .Values.uwsgiExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-metrics-exporter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      org.kobotoolbox.instance: {{ .Release.Name }}-metrics-exporter
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9117"
        prometheus.io/path: "/metrics"
      labels:
        org.kobotoolbox.instance: {{ .Release.Name }}-metrics-exporter
    spec:
      initContainers:
        # Wait for kobocat and kpi
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - dockerize -timeout=120s -wait tcp://{{ .Release.Name }}-kobo:1717 -wait tcp://{{ .Release.Name }}-kobo:1818
      containers:
        - name: kc-uwsgi-exporter
          image: timonwong/uwsgi-exporter:latest
          imagePullPolicy: IfNotPresent
          args:
            - --stats.uri=tcp://{{ .Release.Name }}-kobo:1717
            - --web.telemetry-path=/metrics
            - --log.level={{ .Values.uwsgiExporter.logLevel }}
            - --web.listen-address=9117
          ports:
            - containerPort: 9117
        - name: kpi-uwsgi-exporter
          image: timonwong/uwsgi-exporter:latest
          imagePullPolicy: IfNotPresent
          args:
            - --stats.uri=tcp://{{ .Release.Name }}-kobo:1818
            - --web.telemetry-path=/metrics
            - --log.level={{ .Values.uwsgiExporter.logLevel }}
            - --web.listen-address=9118
          ports:
            - containerPort: 9118
{{- end }}