general:
  externalDomain: localhost
  storageClass: "standard"
  uwsgiExporter:
    enabled: true
global:
  storageClass: "standard"

probes:
  enabled: true

mongodb:
  image:
    registry: ghcr.io
    repository: zcube/bitnami-compat/mongodb
    tag: 5.0.12

postgresql:
  auth:
    host: kobo-postgresql
    username: postgres
    password: admin
    postgresqlUsername: postgres
