apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n-proxy.fullname" . }}
  labels:
    {{- include "n8n-proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n-proxy.selectorLabels" . | nindent 4 }}