apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "growthbook.fullname" . }}
  labels:
    {{- include "growthbook.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "growthbook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "growthbook.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "growthbook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.growthbook.extraEnvVars }}
            - name: {{ $key }}
              value: |-
                {{- tpl $value $ | nindent 16 }}
            {{- end }}
            - name: EMAIL_ENABLED
              value: {{ .Values.growthbook.email.enabled | quote }}
            {{ if .Values.growthbook.email.enabled }}
            - name: EMAIL_HOST
              value: {{ .Values.growthbook.email.host }}
            - name: EMAIL_PORT
              value: {{ .Values.growthbook.email.port | quote }}
            - name: EMAIL_HOST_USER
              value: {{ .Values.growthbook.email.hostUser }}
            - name: EMAIL_HOST_PASSWORD
              value: {{ .Values.growthbook.email.hostPassword }}
            - name: EMAIL_FROM
              value: {{ .Values.growthbook.email.sender }}
            {{ end }}
            - name: MONGODB_URI
              value: {{ include "growthbook.mongo.uri" . }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt-secret
                  name: growthbook-secrets
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  key: encryption-key
                  name: growthbook-secrets
          volumeMounts:
            - name: {{ .Values.volume.name }}
              mountPath: {{ .Values.volume.mountPath }}
          ports:
            - name: frontend-port
              containerPort: 3000
              protocol: TCP
            - name: backend-port
              containerPort: 3100
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      volumes:
        - name: {{ .Values.volume.name }}
          {{ include "growthbook.pvc" . }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
