{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "growthbook.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if eq "-" .Values.persistence.storageClassName }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
{{- end }}