apiVersion: v1
kind: Service
metadata:
  name: {{ include "kutt.fullname" . }}
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: main
      protocol: TCP
      name: main
  selector:
    {{- include "kutt.selectorLabels" . | nindent 4 }}
