apiVersion: v2
name: flagsmith
version: 0.1.1
description: Flagsmith Feature flag and remote configuration solution
type: application
home: https://flagsmith.com/
sources:
  - https://github.com/one-acre-fund/oaf-public-charts/tree/main/charts/flagsmith
maintainers:
  - name: Yann-J
    email: yann.jouanique@gmail.com
dependencies:
  - name: postgresql
    version: ~10.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
